import { SiteNavbar } from '@/components/shared/site-navbar';
import { Footer } from '@/components/landing/footer';

export default function TermsPage() {
  return (
    <>
      <SiteNavbar />
      <div className="mx-auto max-w-2xl px-6 py-16">
        <h1 className="font-display text-3xl font-semibold text-navy-900 mb-2">Terms of Use</h1>
        <p className="text-sm text-navy-400 mb-8">Placeholder — for an academic demonstration project. Not independently legally verified.</p>

        <div className="space-y-6 text-navy-600 text-sm leading-relaxed">
          <section>
            <h2 className="font-display font-semibold text-navy-900 mb-2">Acceptable use</h2>
            <p>EduMind AI is provided for educational demonstration purposes. Do not use it to submit or store real confidential student data without independent legal and security review.</p>
          </section>
          <section>
            <h2 className="font-display font-semibold text-navy-900 mb-2">AI-generated content</h2>
            <p>Content generated by the AI tutor, notes generator, quiz generator, and flashcard generator may contain errors. It is not a substitute for verified instructional material or professional advice.</p>
          </section>
          <section>
            <h2 className="font-display font-semibold text-navy-900 mb-2">No warranty</h2>
            <p>This software is provided "as is" without warranty of any kind, express or implied, per the project's LICENSE file.</p>
          </section>
        </div>
      </div>
      <Footer />
    </>
  );
}
